ALTER TABLE zinnia_entry ADD COLUMN title_en character varying(255);
ALTER TABLE zinnia_entry ADD COLUMN title_es character varying(255);
ALTER TABLE zinnia_entry ADD COLUMN content_en text;
ALTER TABLE zinnia_entry ADD COLUMN content_es text;
ALTER TABLE zinnia_category ADD COLUMN title_en character varying(255);
ALTER TABLE zinnia_category ADD COLUMN title_es character varying(255);
ALTER TABLE zinnia_category ADD COLUMN description_en text;
ALTER TABLE zinnia_category ADD COLUMN description_es text;
ALTER TABLE zinnia_entry ADD COLUMN excerpt_en text;
ALTER TABLE zinnia_entry ADD COLUMN excerpt_es text;